//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WishListWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int WishId { get; set; }
        public string WishType { get; set; }
        public string WishListDesc { get; set; }
        public string CategoryName { get; set; }
    }
}
